### ISSUE TITLE
ShowTypeNames property does not exist (anymore)

### ISSUE THREAD

**Issue by Drachenkaetzchen** [WildGums/Orc.LogViewer#12]
The documentation at http://opensource.wildgums.com/orc.logviewer/ states there should be a property "ShowTypeNames". However, in the most recent version, this doesn't seem to exist anymore.

**Comment by GeertvanHorrik** [comment]
Correct, we replaced it with the new "advanced" filter groups where you can create pre-defined groups and use that instead.

**Comment by Drachenkaetzchen** [comment]
I see. Well, too bad :( Filtering with one click by type would be very awesome. Do you remember with which version this was removed? Maybe I can easily extend the control.

However, the documentation should be fixed.

**Comment by GeertvanHorrik** [comment]
It takes a bit of time to set up the groups once, but they are persisted so we think this is way better. You could even ship it with your app and provide default filter groups for your customers.

**Comment by Drachenkaetzchen** [comment]
Oof, actually I'm putting out new types like crazy, because I have to create one type per supported plugin. It would be extremely difficult to set these up manually, but maybe I can automate it somehow. 

Actually I recently released a new version of my software which now includes Orchestra and Catel, if you're curious you can check it out here: https://presetmagician.com/

**Comment by GeertvanHorrik** [comment]
You can add lots of wildcards (e.g. AssemblyName contains Plugin) or something like that.

**Comment by GeertvanHorrik** [comment]
Just checked out the app, looks great! Needed  a license, but so far the experience was good 👍 

About the types: there must be some sort of special naming convention you are using for plugins (namespace, assembly, typename)? You can simply customize the preset filters at startup and customize it every time you run the app (or install an update).

**Comment by GeertvanHorrik** [comment]
I am going to close the ticket, if you have any further questions, feel free to let us know!
