### ISSUE TITLE
AdvancedLogViewerControl seems not to scroll to the end automatically.

### ISSUE THREAD

**Issue by Katsarakis** [WildGums/Orc.LogViewer#147]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
## Component
Orchestra

## What component is this issue occurring in?
Orchestra.Examples.TaskRunner
[assembly: AssemblyFileVersion("5.2.0")]
[assembly: AssemblyInformationalVersion("5.2.0-alpha.1")]

## Version of Library
latest... Catel 5.11.2

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1.  Start project Orchestra.Examples.TaskRunner
2.  klick Run...again and again. Logging is writing but listbox is not scrolling to the end. 
3.  At Orchestra with Catel 4.5.4 was working.

## Expected Behavior
            <orclogviewer:AdvancedLogViewerControl x:Name="traceOutputControl"  />
traceOutputControl has to scroll automatically at the end

**Comment by Katsarakis** [comment]
I think this is a Orchestra issue?

**Comment by GeertvanHorrik** [comment]
Will be fixed in Orchestra, closing this ticket in favor of https://github.com/WildGums/Orchestra/issues/248
