### ISSUE TITLE
Add Button Start/Stop and stopp autoscrolling

### ISSUE THREAD

**Issue by jensweller** [WildGums/Orc.LogViewer#2]
Hi. A great feature is to have a button to start/stop logging in the Logviewer.
And a button for start/stop autoscrolling. So you have the chance to read a logmessage while lots of new logmessages are recieved.

**Comment by GeertvanHorrik** [comment]
Sounds like a great idea! We would love to see this implemented via a toggle buton. Interested in doing a PR?
