### ISSUE TITLE
Open/Copy buttons

### ISSUE THREAD

**Issue by julesx** [WildGums/Orc.LogViewer#3]
These just crash out.  It's not even clear what they are supposed to do.

**Comment by GeertvanHorrik** [comment]
@mkhomutov , can you check this?

**Comment by mkhomutov** [comment]
sure

**Comment by mkhomutov** [comment]
working good in Orc.LogViewer.Examples project. switching tabs is slow, but no crashing and Open/Copy are working perfect

**Comment by mkhomutov** [comment]
Open is opening txt file with log. Copy just copying it into clipboard

**Comment by julesx** [comment]
http://imgur.com/a/duNuL

perhaps it is related to new visual studio / .net framework.  

some options to disable these buttons would be great!!

**Comment by mkhomutov** [comment]
which version of Windows are you using?

**Comment by mkhomutov** [comment]
please try latest commit

**Comment by mkhomutov** [comment]
I've made changes in other related project

**Comment by julesx** [comment]
everything works great now.  thanks for the snazzy app and quick response guys.

**Comment by GeertvanHorrik** [comment]
On behalf of @mkhomutov : you're welcome :-)

If you have any other issues / ideas, feel free to contact us!
